theme: jekyll-theme-slate
#theme: jekyll-theme-minimal
title: |
  Deep Declarative Networks<br/><br/>
  ECCV 2020 Tutorial
#description: 
#logo: [Location of the logo]
#show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]
